### ISSUE TITLE
Problems to connect the counter

### ISSUE THREAD

**Issue by dl6dbh** [jannickfahlbusch/ha-ppc-smgw#9]
I have now received my Han login from the provider after 3 months. Login via the web interface works. I have entered all the data into the integration, but I am not getting any data from the counter. Is there another trick?

**Comment by jannickfahlbusch** [comment]
Hi,

are there any errors shown in the logs?

You can also try to increase the loglevel using the following in the HA configuration:
```yaml
logger:
  default: info
  logs:
    custom_components.ppc_smgw: debug
```
